__title__ = "historical_sources"
__version__ = "0.0.1"
__author__ = "Vilma Gonzalez"
__email__ = "vilma.gonzalezruiz@gmail.com"
__description__ = "this is mypackage description"
__url__ = "https://github.com/VilmaGlez/historical_sources"
__license__ = "MIT License"
